[tools]
1password-cli = "2.34.0"
age = "1.3.1"
"aqua:cantino/mcfly" = "0.9.4"
aws = { version = "2.34.45", symlink_bins = "true" }
bob = "4.1.7"
delta = "0.19.2"
direnv = "2.37.1"
doggo = "1.1.5"
eza = "0.23.4"
fastfetch = "2.62.1"
fzf = "0.72.0"
gh = "2.92.0"
"github:Ataraxy-Labs/inspect" = "0.1.1"
"github:Ataraxy-Labs/sem" = "0.5.3"
"github:tailcallhq/forgecode" = { version = "2.12.12", bin = "forge" }
lazygit = "0.61.1"
mkcert = "1.4.4"
ripgrep = "15.1.0"
starship = "1.25.1"
tmux = "3.6a"
topgrade = "17.4.0"
viddy = "1.3.0"
yazi = "26.5.6"
zoxide = "0.9.9"
