# builders = ssh-ng://builder@linux-builder aarch64-linux /etc/nix/builder_ed25519 4 - - - c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUpCV2N4Yi9CbGFxdDFhdU90RStGOFFVV3JVb3RpQzVxQkorVXVFV2RWQ2Igcm9vdEBuaXhvcwo=; ssh-ng://orb aarch64-linux ; ssh-ng://orb x86_64-linux ;
builders = ssh-ng://orb aarch64-linux ; ssh-ng://orb x86_64-linux ;
# ssh://steamdeck x86_64-linux ;

builders-use-substitutes = true
